### ISSUE TITLE
What dataset has been used for training?

### ISSUE THREAD

**Issue by ArchanGhosh** [neuroneural/brainchop#15]
If you can kindly share what dataset has been used for training, especially the segmentation that would be helpful, as we are working on a CNN based segmentation where we are looking for brain MRI segmentations.

**Comment by Mmasoud1** [comment]
Thank you for the question, please kindly use [Discussions Q&A](https://github.com/neuroneural/brainchop/discussions/categories/q-a) board for any further questions.  We used the Human Connectome Project (HCP), which  is an open-access dataset.

**Comment by ArchanGhosh** [comment]
Ty and sorry will keep it to Discussions
