### ISSUE TITLE
A confusing menu of available models

### ISSUE THREAD

**Issue by sergeyplis** [neuroneural/brainchop#21]
The current list of models looks very messy and does not leave a feeling of what is unique and important about brainchop. 
Minimally, I suggest the following modification that leaves the content as is but makes it clear by the order which models are unique and powerful:

1.  Full Brain Single Pass GWM
2.  50-ROI Atlas
    - low mem, slower
    - high mem, faster (may not run)
3. 104-ROI FS aparc+aseg Atlas
    - low mem, slower
    - high mem, faster (may not run)
4. Gray-White Matter (large)
    - low mem, slower
    - high mem, faster (may not run)

Leave only the above under models. Just 4 models and 2 ways to run them. Eventually we may make the choice which of the ways to run a model automatic based on the users browser capabilities.

If we want to still enable the user to perform the two operations that are currently cluttering the menu without adding to clarity and much to functionality, let's inside the "Models" menu add a divider line for "Operations" followed by:

1. Extract the Brain (large)
2. Extract the Brain (light)
3. Compute Brain Mask (light)
4. Compute Brain Mask (large)

Ideally, the above menu also contains only 2 operations: extract and compute.

**Comment by Mmasoud1** [comment]
List updated
