### ISSUE TITLE
current version fails at Cortical Atlas 50 (failsafe)

### ISSUE THREAD

**Issue by sergeyplis** [neuroneural/brainchop#23]
The Cortical Atlas 50 (failsafe) model fails as follows:
<img width="1383" alt="image" src="https://github.com/neuroneural/brainchop/assets/981291/f1e9239d-c05c-47cf-a271-c96c0de1d1de">
in the following commit:
https://github.com/neuroneural/brainchop/commit/b12fec8baec7efcd748df88a5c380b6c55b79778
This is an M2 laptop with 64Gb of RAM.

**Comment by sergeyplis** [comment]
https://github.com/neuroneural/brainchop/pull/24/commits/e73a51f12ca50fe525b31a7ed8e1270d8095d66b this commit fixes the problem
Please review the PR

**Comment by sergeyplis** [comment]
https://github.com/neuroneural/brainchop/pull/24 updated PR

**Comment by Mmasoud1** [comment]
Merged
