### ISSUE TITLE
Will version 3 support the same features as version 4？

### ISSUE THREAD

**Issue by samulenzz** [neuroneural/brainchop#40]
Will version 3 support the same features as version 4，such as input 3D , output volumes？

**Comment by samulenzz** [comment]
@Mmasoud1 Thanks for your reply. That's exactly what I want to ask. Will the input 3D enhancement and output 3D options and will also be included in v4?

**Comment by Mmasoud1** [comment]
@samulenzz , We hope so,  and that is why we left v3 active also to help our respected user like you.

**Comment by sergeyplis** [comment]
@samulenzz I wonder what you mean by "output 3D options"? Do you mean saving the resulting segmentation as a nifti file? In current brainchop.org you can do it as before
<img width="577" alt="image" src="https://github.com/neuroneural/brainchop/assets/981291/27db6c6c-eb62-4930-9b7f-13637df42722">
Press "Save Overlay" and name the output file any way you want in the save file dialogue

**Comment by Mmasoud1** [comment]
@sergeyplis ,   samulenzz  means that part by  "output 3D options"   in brainchop v3.
![image](https://github.com/neuroneural/brainchop/assets/36082112/6b57999e-1160-4dc4-9e01-07780a923701)
